scheb_two_factor:
    google:
        enabled: false
        server_name: "WachZeit"      # Server name used in QR code
        issuer: "WachZeit"        # Issuer name used in QR code
        digits: 6
        leeway: 0   # Acceptable time drift in seconds, must be less or equal than 30 seconds
        template: security/google_auth_code_input.html.twig   # Template used to render the authentication form
